"""
OnsetLab API Agent Generator
============================
Generates agent files by copying base_agent.py and creating config files.
Clean, config-driven architecture - no string templating of Python code.
"""

import json
from pathlib import Path
from typing import Optional

# Get the base agent code
_dir = Path(__file__).parent
_base_agent_path = _dir / "base_agent.py"


def _load_base_agent() -> str:
    """Load the base agent code."""
    with open(_base_agent_path, "r") as f:
        return f.read()


# ============================================================================
# Templates for non-Python files
# ============================================================================

ENV_TEMPLATE = '''# {agent_name} Environment Variables
# Copy this to .env and fill in your values

# LLM API Key (required - choose one)
OPENAI_API_KEY=
ANTHROPIC_API_KEY=

# Service Credentials
{env_vars}
'''

REQUIREMENTS_TEMPLATE = '''# {agent_name} Requirements
openai>=1.0.0
anthropic>=0.18.0
python-dotenv>=1.0.0
'''


def _build_readme(agent_name: str, service_credentials: str, service_docs: str, config_notes: str) -> str:
    """Build README content."""
    readme = f'''# {agent_name}

Generated by [OnsetLab](https://github.com/riyanshibohra/onsetlab)

## Quick Start

1. Install dependencies:
   ```bash
   pip install -r requirements.txt
   ```

2. Set up your API keys:
   ```bash
   cp .env.example .env
   # Edit .env and add your keys
   ```

3. Run the agent:
   ```bash
   python agent.py
   ```

## Required API Keys

**LLM Provider (choose one):**
- `OPENAI_API_KEY` - https://platform.openai.com/api-keys
- `ANTHROPIC_API_KEY` - https://console.anthropic.com/

**Service Credentials:**
{service_credentials}

## MCP Server Documentation

Review each MCP server's documentation for setup details and configuration options:

{service_docs}
'''
    
    if config_notes:
        readme += f'''
## Important Configuration Notes

{config_notes}
'''
    
    readme += '''
## Usage

Type your requests naturally:
- "show me open issues"
- "list my calendar events"  
- "search for X"

Type "quit" or "exit" to stop.
'''
    return readme


# ============================================================================
# Generator Functions
# ============================================================================

def generate_config(
    agent_name: str,
    skill_summary: str,
    api_provider: str = "openai",
    model: str = "gpt-4o"
) -> dict:
    """Generate the main config.json content."""
    return {
        "agent_name": agent_name,
        "skill_summary": skill_summary,
        "api_provider": api_provider,
        "model": model
    }


def generate_tools_json(servers: list[dict]) -> list[dict]:
    """Generate the tools.json content from server configs."""
    all_tools = []
    for server in servers:
        server_tools = server.get("tools", [])
        for tool in server_tools:
            if isinstance(tool, dict):
                all_tools.append({
                    "name": tool.get("name", ""),
                    "description": tool.get("description", ""),
                    "parameters": tool.get("parameters", {}),
                    "required_params": tool.get("required_params", [])
                })
            elif isinstance(tool, str):
                all_tools.append({
                    "name": tool,
                    "description": f"Tool: {tool}",
                    "parameters": {}
                })
    return all_tools


def generate_mcp_config(servers: list[dict]) -> list[dict]:
    """Generate the mcp_config.json content."""
    mcp_config = []
    for server in servers:
        mcp_config.append({
            "name": server.get("name", server.get("service", "unknown")),
            "package": server.get("package", {}),
            "auth": server.get("auth", {}),
            "tools": [
                t.get("name") if isinstance(t, dict) else t
                for t in server.get("tools", [])
            ]
        })
    return mcp_config


def generate_env_example(agent_name: str, servers: list[dict]) -> str:
    """Generate .env.example content."""
    env_vars = []
    seen = set()
    
    for server in servers:
        auth = server.get("auth", {})
        for var in auth.get("env_vars", []):
            if var not in seen:
                seen.add(var)
                env_vars.append(f"{var}=")
    
    return ENV_TEMPLATE.format(
        agent_name=agent_name,
        env_vars="\n".join(env_vars)
    )


def generate_readme(agent_name: str, servers: list[dict]) -> str:
    """Generate README.md content with service docs and config notes."""
    # Build service credentials section
    credential_lines = []
    seen_vars = set()
    
    for server in servers:
        auth = server.get("auth", {})
        setup_url = auth.get("setup_url", "")
        for var in auth.get("env_vars", []):
            if var not in seen_vars:
                seen_vars.add(var)
                if setup_url:
                    credential_lines.append(f"- `{var}` - {setup_url}")
                else:
                    credential_lines.append(f"- `{var}`")
    
    if not credential_lines:
        credential_lines.append("- No service credentials required")
    
    # Build service documentation links section
    doc_lines = []
    for server in servers:
        name = server.get("name", server.get("service", "Unknown"))
        source = server.get("source", "")
        description = server.get("description", "")[:100]
        
        if source:
            doc_lines.append(f"- **{name}**: {source}")
            if description:
                doc_lines.append(f"  - {description}")
        else:
            doc_lines.append(f"- **{name}**")
    
    # Build configuration notes for services that need special setup
    config_notes = []
    for server in servers:
        service_id = server.get("service", server.get("service_id", "")).lower()
        auth = server.get("auth", {})
        guide = auth.get("guide", {})
        
        # Special notes for filesystem
        if service_id == "filesystem":
            config_notes.append('''**File System:**
The filesystem MCP server requires you to specify which directories the agent can access.
Edit `mcp_config.json` and add allowed paths to the `args` array:
```json
"args": ["-y", "@modelcontextprotocol/server-filesystem", "/path/to/allowed/dir1", "/path/to/allowed/dir2"]
```
For security, only the specified directories will be accessible.''')
        
        # Add any special notes from the registry
        elif guide.get("notes"):
            config_notes.append(f"**{server.get('name', service_id)}:** {guide['notes']}")
    
    return _build_readme(
        agent_name, 
        "\n".join(credential_lines),
        "\n".join(doc_lines),
        "\n\n".join(config_notes)
    )


def generate_requirements(agent_name: str) -> str:
    """Generate requirements.txt content."""
    return REQUIREMENTS_TEMPLATE.format(agent_name=agent_name)


# ============================================================================
# Main Generation Function
# ============================================================================

def generate_api_agent(
    agent_name: str,
    skill_summary: str,
    filtered_servers: list[dict],
    api_provider: str = "openai",
    model: str = "gpt-4o"
) -> dict:
    """
    Generate all files needed for an API-based agent.
    
    Returns a dict mapping filenames to their contents.
    """
    files = {}
    
    # Main agent code (copy of base_agent.py)
    files["agent.py"] = _load_base_agent()
    
    # Config files
    files["config.json"] = json.dumps(
        generate_config(agent_name, skill_summary, api_provider, model),
        indent=2
    )
    
    files["tools.json"] = json.dumps(
        generate_tools_json(filtered_servers),
        indent=2
    )
    
    files["mcp_config.json"] = json.dumps(
        generate_mcp_config(filtered_servers),
        indent=2
    )
    
    # Support files
    files[".env.example"] = generate_env_example(agent_name, filtered_servers)
    files["requirements.txt"] = generate_requirements(agent_name)
    files["README.md"] = generate_readme(agent_name, filtered_servers)
    
    return files
